channels:
  - conda-forge
  - cta-observatory
dependencies:
  - python=3.7
  # - ctools=1.7.4  -> not found for POWER9
  - astropy
  # - healpy -> will produce conflicts with tensorflow-gpu 2.4.3 + astropy 4.2 on for POWER9
  - pandas
  #- xml -> not found for POWER9
  - pyaml
  - scipy
  #- pyregion -> not found for POWER9
  - seaborn
#  - untangle  # required ONLY by the old version of the pipeline (folder "thesis")
