#!/bin/bash
echo gammapy1d_binned_fit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/gammapy1d_binned_fit.sh
echo gammapy3d_fit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/gammapy3d_fit.sh
echo ctools1d_fit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/ctools1d_fit.sh
echo gammapy3d_binned_blindfit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/gammapy3d_binned_blindfit.sh
echo ctools3d_binned_fit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/ctools3d_binned_fit.sh
echo ctools3d_blindfit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/ctools3d_blindfit.sh
echo ctools3d_binned_blindfit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/ctools3d_binned_blindfit.sh
echo gammapy3d_blindfit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/gammapy3d_blindfit.sh
echo ctools3d_fit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/ctools3d_fit.sh
echo gammapy1d_fit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/gammapy1d_fit.sh
echo gammapy3d_binned_fit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/gammapy3d_binned_fit.sh
echo ctools1d_binned_fit.sh
bash /data01/homes/cta/gammapy_integration/cta-sag-sci/jobs/ctools1d_binned_fit.sh
